module.exports = {
  core: {
    LayerTimeContext     : require('./dist/core/layer-time-context'),
    Layer                : require('./dist/core/layer'),
    namespace            : require('./dist/core/namespace'),
    TimelineTimeContext  : require('./dist/core/timeline-time-context'),
    Timeline             : require('./dist/core/timeline'),
    TrackCollection      : require('./dist/core/track-collection'),
    Track                : require('./dist/core/track'),
  },
  shapes: {
    AnnotatedMarker      : require('./dist/shapes/annotated-marker'),
    AnnotatedSegment     : require('./dist/shapes/annotated-segment'),
    BaseShape            : require('./dist/shapes/base-shape'),
    Cursor               : require('./dist/shapes/cursor'),
    Dot                  : require('./dist/shapes/dot'),
    Line                 : require('./dist/shapes/line'),
    Marker               : require('./dist/shapes/marker'),
    Segment              : require('./dist/shapes/segment'),
    Ticks                : require('./dist/shapes/ticks'),
    TracePath            : require('./dist/shapes/trace-path'),
    TraceDots            : require('./dist/shapes/trace-dots'),
    Waveform             : require('./dist/shapes/waveform'),
  },
  behaviors: {
    BaseBehavior         : require('./dist/behaviors/base-behavior'),
    BreakpointBehavior   : require('./dist/behaviors/breakpoint-behavior'),
    MarkerBehavior       : require('./dist/behaviors/marker-behavior'),
    SegmentBehavior      : require('./dist/behaviors/segment-behavior'),
    TimeContextBehavior  : require('./dist/behaviors/time-context-behavior'),
    TraceBehavior        : require('./dist/behaviors/trace-behavior'),
  },
  interactions: {
    EventSource          : require('./dist/interactions/event-source'),
    Keyboard             : require('./dist/interactions/keyboard'),
    Surface              : require('./dist/interactions/surface'),
    WaveEvent            : require('./dist/interactions/wave-event'),
  },
  states: {
    BaseState            : require('./dist/states/base-state'),
    BreakpointState      : require('./dist/states/breakpoint-state'),
    BrushZoomState       : require('./dist/states/brush-zoom-state'),
    CenteredZoomState    : require('./dist/states/centered-zoom-state'),
    ContextEditionState  : require('./dist/states/context-edition-state'),
    EditionState         : require('./dist/states/edition-state'),
    SelectionState       : require('./dist/states/selection-state'),
    SimpleEditionState   : require('./dist/states/simple-edition-state'),
  },
  helpers: {
    AnnotatedMarkerLayer : require('./dist/helpers/annotated-marker-layer'),
    BreakpointLayer      : require('./dist/helpers/breakpoint-layer'),
    CursorLayer          : require('./dist/helpers/cursor-layer'),
    GridAxisLayer        : require('./dist/helpers/grid-axis-layer'),
    MarkerLayer          : require('./dist/helpers/marker-layer'),
    SegmentLayer         : require('./dist/helpers/segment-layer'),
    TimeAxisLayer        : require('./dist/helpers/time-axis-layer'),
    TraceLayer           : require('./dist/helpers/trace-layer'),
    WaveformLayer        : require('./dist/helpers/waveform-layer'),
  },
  axis: {
    AxisLayer            : require('./dist/axis/axis-layer'),
    timeAxisGenerator    : require('./dist/axis/time-axis-generator'),
    gridAxisGenerator     : require('./dist/axis/grid-axis-generator'),
  },
  utils: {
    format               : require('./dist/utils/format'),
    OrthogonalData       : require('./dist/utils/orthogonal-data'),
    scales               : require('./dist/utils/scales'),
  }
}
